# @Author : zhangfan
# @email  : 61316173 @qq.com @Date   : 2026-02-04
# Copyright (c) 2026 61316173 @qq.com. All Rights Reserved.
#
# NOTICE:  All information contained herein is, and remains
# the property of the author. The intellectual and technical concepts
# contained herein are proprietary to the author and are protected
# by trade secret or copyright law. Dissemination of this information
# or reproduction of this material is strictly forbidden unless prior
# written permission is obtained from the author.

# 实验元数据
exp_name: "medical_gpt2_v1_baseline"

# 数据配置
data:
  version: "v1"
  train_path: "data/v1/processed/train.pt"
  val_path: "data/v1/processed/val.pt"
  vocab_path: "data/v1/processed/vocab.json"
  maxlen: 128

# 模型配置
model:
  type: "gpt2_v1"
  n_layer: 2
  n_head: 2
  n_embd: 128
  dropout: 0.1

# 训练配置
train:
  epochs: 500
  batch_size: 4
  lr: 0.0005
  device: "auto" # "cuda", "cpu", or "auto"
